# Generated by Django 3.1.7 on 2021-04-01 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, default='', max_length=50)),
                ('revision', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('publish_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('characters', models.ManyToManyField(to='resources.Character')),
                ('places', models.ManyToManyField(to='resources.Place')),
                ('subjects', models.ManyToManyField(to='resources.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.libraryuser')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='loans',
            field=models.ManyToManyField(through='resources.Loan', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
