# Generated by Django 3.0.10 on 2021-04-03 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210403_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='check_out_date',
            field=models.DateField(default=datetime.date(2021, 4, 3)),
        ),
    ]
