# Generated by Django 3.1.7 on 2021-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('resources', '0004_auto_20210402_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
    ]
