# Generated by Django 3.1.7 on 2021-04-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210402_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='author_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.author'),
        ),
    ]
