# Generated by Django 3.1.7 on 2021-04-02 18:08

from django.db import migrations

def populateAuthorModel(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    Author = apps.get_model('resources', 'Author')
    for book in Resource.objects.all():
        author, created = Author.objects.get_or_create(name=book.author)
        book.author_link = author
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210402_1907'),
    ]

    operations = [
        migrations.RunPython(populateAuthorModel),
    ]
