# Generated by Django 3.1.7 on 2021-04-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_transfer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
    ]
