# Generated by Django 3.1.7 on 2021-04-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_remove_resource_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='author_link',
            new_name='author',
        ),
    ]
