# Generated by Django 3.1.7 on 2021-04-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210402_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
