# Generated by Django 3.1.7 on 2021-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20210402_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
