# Generated by Django 3.1.7 on 2021-04-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20210402_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.location'),
        ),
    ]
